site_name: CNC Training 
theme: 
  name: material 
  font:
    text: Malgun Gothic
    code: Cascadia Mono
  palette:
    scheme: slate
plugins:
    - mkdocs-video  

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true # Renders beautiful icons instead of standard HTML checkboxes
      clickable_checkbox: true


nav:
  - Agenda: index.md
  - TwinCAT 3 Overview : TC_QuickStart.md
  - System Maintenance: Maintenance.md
  - Servo_AX5000 : Servo_AX5.md
  - TwinCAT CNC: TC_CNC.md
  - EtherCAT Diagnosis: EtherCATDiag.md
  - CNC Diagnosis : CNC_Diag.md
  - CNC_Distance Control : DistCtrl.md
  - Tuning : Tuning.md
  - QA : QA.md
  - Contact: Contact.md 
